-- Table: screen_details
-- Oracle version of screen_details DDL and insert

DROP TABLE screen_details CASCADE CONSTRAINTS;

CREATE TABLE screen_details (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
    screen_id NUMBER(19) NOT NULL,
    screen_name VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT screen_details_pkey PRIMARY KEY (id)
);

INSERT INTO screen_details (screen_id, screen_name, created_at, updated_at, is_active)
VALUES
(1, 'callback', SYSTIMESTAMP, NULL, 1),
(2, 'applyProducts', SYSTIMESTAMP, NULL, 1);
