-- Table: configuration_field_options
-- Oracle version of configuration_field_options DDL and insert

DROP TABLE configuration_field_options CASCADE CONSTRAINTS;

CREATE TABLE configuration_field_options (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
    configuration_id NUMBER(19) NOT NULL,
    english_option_value VARCHAR2(255) NOT NULL,
    arabic_option_value VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    is_active NUMBER(1),
    CONSTRAINT configuration_field_options_pkey PRIMARY KEY (id),
    CONSTRAINT configuration_field_options_configuration_id_fkey FOREIGN KEY (configuration_id)
        REFERENCES configurations (id)
        ON DELETE CASCADE
);

INSERT INTO configuration_field_options
(
    configuration_id,
    english_option_value,
    arabic_option_value,
    created_at,
    updated_at,
    is_active
)
VALUES
-- 1️⃣ General Inquiry
(30,
 'General Inquiry',
 'استفسار عام',
 SYSTIMESTAMP,
 SYSTIMESTAMP,
 1
),

-- 2️⃣ Product Information
(30,
 'Product Information',
 'معلومات عن المنتج',
 SYSTIMESTAMP,
 SYSTIMESTAMP,
 1
),

-- 3️⃣ Complaint
(30,
 'Complaint',
 'شكوى',
 SYSTIMESTAMP,
 SYSTIMESTAMP,
 1
),

-- 4️⃣ Feedback
(30,
 'Feedback',
 'ملاحظات',
 SYSTIMESTAMP,
 SYSTIMESTAMP,
 1
),

-- 5️⃣ Callback Request
(30,
 'Callback Request',
 'طلب مكالمة',
 SYSTIMESTAMP,
 SYSTIMESTAMP,
 1
);